import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int seed = Integer.parseInt(args[1]);
        Random generator = new Random(seed);  
		int T = Integer.parseInt(args[0]);
		int familiesOf2 = 0;
		int familiesOf3 = 0;
		int familiesOf4OrMore = 0;
		double average = 0;
		for(int tests = 1; tests <= T;tests++ )
		{
			boolean both= false;
		    int boys=0;
		    int girls = 0;
		    while (both != true)
		    {
			   double birth = generator.nextDouble();
			   if (birth>=0.5)
			     {
			  	    boys++;
			     } else 
			        {
				      girls++;
			        }
			   if (boys>=1 && girls>=1)
			        both = true;

			}
			if ((boys+girls)==2)
			{
				familiesOf2++;
			} else if ((boys+girls) == 3)
			{
				familiesOf3++;
			} else
			 {
				familiesOf4OrMore ++;
			 }
			average = average + (boys+girls);
	    }
		System.out.println("Average: " + (average/T) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + familiesOf2);
		System.out.println("Number of families with 3 children: " + familiesOf3);
		System.out.println("Number of families with 4 or more children: " + familiesOf4OrMore);
		int mostCommom =Math.max(familiesOf2,(Math.max(familiesOf3, familiesOf4OrMore)));
		if (mostCommom==familiesOf2)
		{
			System.out.println("The most common number of children is 2.");
		} else 
		{
			if (mostCommom==familiesOf3)
			{
				System.out.println("The most common number of children is 3.");
			} else
		       {
			   System.out.println("The most common number of children is 4 or more.");
		       }
		 } 

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
